### ISSUE TITLE
When running JWT in an Azure WebJob or Function, you will get an error

### ISSUE THREAD

**Issue by kendomen** [box/box-windows-sdk-v2#297]
When running JWT in an Azure WebJob or Function, you will get an error: 
           System.Security.Cryptography.CryptographicException: The system cannot find the file specified.
            The error message is misleading and you can see more details on it here:    
             https://blogs.msdn.microsoft.com/winsdk/2009/11/16/opps-system-security-cryptography-cryptographicexception-the-system-cannot-find-the-file-specified/

In order to fix this, I had to make changes to BoxJWTAuth:

 public BoxJWTAuth(IBoxConfig boxConfig)
        {
            this.boxConfig = boxConfig;

            // ------------------------------------------------------------------
            // Note:  When running JWT in an Azure WebJob or Function, you will get an error: 
            //           System.Security.Cryptography.CryptographicException: The system cannot find the file specified.
            //        The error message is misleading and you can see more details on it here:    
            //        https://blogs.msdn.microsoft.com/winsdk/2009/11/16/opps-system-security-cryptography-cryptographicexception-the-system-cannot-find-the-file-specified/
            // ------------------------------------------------------------------

            var pwf = new PEMPasswordFinder(this.boxConfig.JWTPrivateKeyPassword);
            AsymmetricCipherKeyPair key;

            using (var reader = new StringReader(this.boxConfig.JWTPrivateKey))
            {
                key = (AsymmetricCipherKeyPair)new PemReader(reader, pwf).ReadObject();
            }

            // ------------------------------------------------------------------
            // This is the original call to BouncyCastle
            // var rsa = DotNetUtilities.ToRSA((RsaPrivateCrtKeyParameters)key.Private);
            // ------------------------------------------------------------------
            var rsa = ToRSA((RsaPrivateCrtKeyParameters)key.Private);   // use the local overriden version instead!!!
            
#if NETSTANDARD1_4
            this.credentials = new SigningCredentials(new RsaSecurityKey(rsa), SecurityAlgorithms.RsaSha256);
#else
            this.credentials = new SigningCredentials(new RsaSecurityKey(rsa), SecurityAlgorithms.RsaSha256Signature, SecurityAlgorithms.Sha256Digest);
          
#endif
        }
       
        // -------------------------------- start KD Added 3-7-17 ------------------------------
        // Took the guts of the sealed class in DotNetUtilities and overrode it here
        // -------------------------------------------------------------------------------------
        public static RSA ToRSA(RsaPrivateCrtKeyParameters privKey)
        {
            return CreateRSAProvider(ToRSAParameters(privKey));
        }

        private static RSA CreateRSAProvider(RSAParameters rp)
        {
            CspParameters csp = new CspParameters();
            csp.KeyContainerName = string.Format("BouncyCastle-{0}", Guid.NewGuid());

            // This needs to be here to run as WebJob
            csp.Flags = CspProviderFlags.UseMachineKeyStore;

            RSACryptoServiceProvider rsaCsp = new RSACryptoServiceProvider(csp);
            rsaCsp.ImportParameters(rp);

            return rsaCsp;
        }

        // ------------------------------- This is crazy!!! This throws BadData -------------------
        /**public static RSAParameters ToRSAParameters(RsaKeyParameters rsaKey)
        {
            RSAParameters rp = new RSAParameters();
            rp.Modulus = rsaKey.Modulus.ToByteArrayUnsigned();
            if (rsaKey.IsPrivate)
                rp.D = ConvertRSAParametersField(rsaKey.Exponent, rp.Modulus.Length);
            else
                rp.Exponent = rsaKey.Exponent.ToByteArrayUnsigned();
            return rp;
        }

        private static byte[] ConvertRSAParametersField(BigInteger n, int size)
        {
            byte[] bs = n.ToByteArrayUnsigned();

            if (bs.Length == size)
                return bs;

            if (bs.Length > size)
                throw new ArgumentException("Specified size too small", "size");

            byte[] padded = new byte[size];
            Array.Copy(bs, 0, padded, size - bs.Length, bs.Length);
            return padded;
        }
    **/
        // ------------------------------- end This is crazy!!! This throws BadData -------------------

        // ------------------------------------------------------------------------------------------------------------------
        // OMG!!! http://stackoverflow.com/questions/28370414/import-rsa-key-from-bouncycastle-sometimes-throws-bad-data
        // ------------------------------------------------------------------------------------------------------------------
        public static RSAParameters ToRSAParameters(RsaPrivateCrtKeyParameters privKey)
        {
            RSAParameters rp = new RSAParameters();
            rp.Modulus = privKey.Modulus.ToByteArrayUnsigned();
            rp.Exponent = privKey.PublicExponent.ToByteArrayUnsigned();
            rp.P = privKey.P.ToByteArrayUnsigned();
            rp.Q = privKey.Q.ToByteArrayUnsigned();
            rp.D = ConvertRSAParametersField(privKey.Exponent, rp.Modulus.Length);
            rp.DP = ConvertRSAParametersField(privKey.DP, rp.P.Length);
            rp.DQ = ConvertRSAParametersField(privKey.DQ, rp.Q.Length);
            rp.InverseQ = ConvertRSAParametersField(privKey.QInv, rp.Q.Length);
            return rp;
        }

        private static byte[] ConvertRSAParametersField(BigInteger n, int size)
        {
            byte[] bs = n.ToByteArrayUnsigned();
            if (bs.Length == size)
                return bs;
            if (bs.Length > size)
                throw new ArgumentException("Specified size too small", "size");
            byte[] padded = new byte[size];
            Array.Copy(bs, 0, padded, size - bs.Length, bs.Length);
            return padded;
        }
        // -------------------------------- end KD Added 3-7-17 ------------------------------

**Comment by coolboy** [comment]
Hi @kendomen 

Thank you so much for the contribution, could you send us a pull request so that we can merge this fix quicker?

**Comment by kendomen** [comment]
Yes I'll do that.

Thanks!

Sent from my iPhone

On Mar 28, 2017, at 4:20 PM, Yang Hu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @kendomen<https://github.com/kendomen>

Thank you so much for the contribution, could you send us a pull request so that we can merge this fix quicker?

**Comment by ahawes-clarity** [comment]
Thanks for finding and addressing this issue. I would have been lost for a while for sure trying to track it down myself. I am hoping your updates can be pulled in and tested soon so I can make use of them.

**Comment by kendomen** [comment]
Ok, the pull request is created:  https://github.com/box/box-windows-sdk-v2/pull/300

**Comment by coolboy** [comment]
fixed in #301

**Comment by ahawes-clarity** [comment]
I pulled the latest from Master and built and used the new assemblies in my Azure Functions App and I am still getting the same error. This is outside my skill level so any help would be appreciated.

	2017-04-03T10:26:14.745 BoxConnector.GetFile Exception: The system cannot find the file specified.
	 -    at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
	   at System.Security.Cryptography.Utils._CreateCSP(CspParameters param, Boolean randomKeyContainer, SafeProvHandle& hProv)
	   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
	   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
	   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
	   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
	   at Org.BouncyCastle.Security.DotNetUtilities.CreateRSAProvider(RSAParameters rp)
	   at Box.V2.JWTAuth.BoxJWTAuth..ctor(IBoxConfig boxConfig)
	   at AquasolConnect.BoxConnector.Box.BoxService..ctor(String clientId, String clientSecret, String enterpriseId, String privateKeyPassword, String publicKeyId)
	   at AquasolConnect.BoxConnector.Connector.get_BoxService()
	   at AquasolConnect.BoxConnector.Connector.GetFile(String fileId)
	   at Submission#0.Run(HttpRequestMessage req, TraceWriter log) in :line 61

**Comment by kendomen** [comment]
Can you show me the code for:  BoxConnector.GetFile?

**Comment by coolboy** [comment]
@kendomen @ahawes-clarity I think this is related to the implementation in Org.BouncyCastle.Security.DotNetUtilities.CreateRSAProvider(), they are missing the csp.Flags = CspProviderFlags.UseMachineKeyStore; => https://github.com/bcgit/bc-csharp/blob/master/crypto/src/security/DotNetUtilities.cs#L234

So #301 will fix this problem in net-core, but not pcl, since pcl is using the BouncyCastle's DotNetUtilities instead of our own one

**Comment by ahawes-clarity** [comment]
@kendomen Here is the relevant call deeper down in my code.

        public GetFileResponse GetFile(string fileId)
        {
            return GetFileAsync(fileId).Result;
        }

        private async Task<GetFileResponse> GetFileAsync(string fileId)
        {
            try
            {
                var file = await BoxClient.FilesManager.DownloadStreamAsync(fileId);
                return new GetFileResponse(file.ToByteArray());
            }
            catch (Exception ex)
            {
                return new GetFileResponse(ex.Message);
            }
        }

@coolboy That would seem to make sense. How does something like this get resolved?

**Comment by coolboy** [comment]
Hi @ahawes-clarity 

Is it possible you can modify our source code and change Box.V2 to use Box.V2.Core/DotNetUtilities.cs instead of Org.BouncyCastle.Security.DotNetUtilities?

I would like to have enough feedback before we are going to override BouncyCastle implementation in PCL.

**Comment by ahawes-clarity** [comment]
Unfortunately, I am not really able to do this. I am working on client time and I can't really justify the time without their approval. I did try to see if I could do something quickly but ran into issues related to my environment and .Net Core versions so I stopped. I am happy to test however.

I will just tell the client we can't move forward until this issue is fixed in the SDK.

Thanks

**Comment by ahawes-clarity** [comment]
Any update on when this issue will be fixed?

**Comment by coolboy** [comment]
@ahawes-clarity I will check to see if this will be in our next release, which is coming by next week

**Comment by ahawes-clarity** [comment]
Thanks. Did you all decide to override BouncyCastle implementation in PCL?

**Comment by coolboy** [comment]
that's what I need to discuss with the team

**Comment by coolboy** [comment]
Hi @ahawes-clarity ,

By look deeper into the issue, I believe the right way is to expose a flag and let user to choose the way to store the key.

Since when we use machine key stores, any user in that machine may have access to those keys.

So I don't think we will have time to make it into the coming release, but if this is urgent, I can send you a private build of this fix in pcl sometime later

Let me know what do you think

Ref:
https://blogs.msdn.microsoft.com/alejacma/2007/12/03/rsacryptoserviceprovider-fails-when-used-with-asp-net/

**Comment by ahawes-clarity** [comment]
Thanks @coolboy,

I understand. Yes, please do send me a private build when you have it ready.

And, just as a reminder, I am trying to use this in the context of an Azure Functions app. I am not sure what exactly you mean by "expose a flag and let user to choose the way to store the key" but to be useful for me I need it to be something I can do in Azure Functions.

Thanks again.

**Comment by coolboy** [comment]
Hi @ahawes-clarity ,

Please find the private build here -> https://app.box.com/s/p2xshdp6y04lry4fvg6zco8vbre9keio

This file is not fully tested and not officially supported by us, but feedback is welcome and which will help us to consider make it into our next release.

Hope this will make your life easier ;)

**Comment by ahawes-clarity** [comment]
Thanks. I give it a try first thing next week.

**Comment by cburnette** [comment]
@coolboy Hey Yang, I just tried this out in an Azure function and your patched build does indeed work.  It would be cool to get this fix into a release so people can start to use azure functions.

**Comment by coolboy** [comment]
@cburnette working on it

**Comment by ahawes-clarity** [comment]
For what it is worth, I can also confirm @coolboy's fix worked for me.

**Comment by coolboy** [comment]
Thanks for everyone's support here ;)

**Comment by EagleLize** [comment]
Hi coolboy,
I am using Box.V2(2.15.5), Box.V2.JWTAuth(1.3.1) and System.IdentityModel.Token.Jwt(4.02.206221351) on my project, it worked locally but not in Azure.  Am I using correct version?
Thanks.
Johnny

**Comment by coolboy** [comment]
Hi @EagleLize ,

What's the error are you seeing?

**Comment by EagleLize** [comment]
The system cannot find the file specified.

**Comment by coolboy** [comment]
I should fix that problem in 2.15.5

do you have a full stack trace? and mind if try this private build? https://app.box.com/s/p2xshdp6y04lry4fvg6zco8vbre9keio

**Comment by EagleLize** [comment]
I am using it in a .NET core class library project that I can only references with what in Nuget Package.  Is the Box.V2.Core fixed this issue as well?  I see there is Box.V2.Core in Nuget.

**Comment by coolboy** [comment]
Box.V2.Core should fix this issue as well, and you can see the fix here -> https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2.JWTAuth/RSAUtilities.cs#L27

Do you have a detailed repo step and I will see what can I find out in my side

**Comment by EagleLize** [comment]
Thanks coolboy.
I am getting this error when upload to Azure

Could not load file or assembly 'System.Security.Claims, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by coolboy** [comment]
@EagleLize 

So it's a different issue, but I don't know what's the fix, seems related to azure environment.

What's your azure environment to repo this problem?

Here is what I have found out online, just FYI
https://www.codeproject.com/questions/817546/could-not-load-type-system-security-claims-claimsi

**Comment by cburnette** [comment]
The fix is in place in the Core project but not in the PCL project.  I believe the team is adding the fix to the PCL build for the next version.  I’ve verified that the fix does allow for Azure function to work correctly.

Chad

**Comment by coolboy** [comment]
fixed in this version
https://github.com/box/box-windows-sdk-v2/releases/tag/v2.15.6
